### PR TITLE
Fix for "inactivity timeout (--ping-restart) restarting"

### PR DESCRIPTION
**Pull request by dwilches**
Hello,

I was getting disconnected from the VPN after 30 minutes until I added this line. So sending a PR in case this is useful for others.

Regards.

### CODE REVIEW

**Review by rdvencioneck — APPROVED** [review]

**Comment by rdvencioneck** [comment]
Hi @dwilches 
Thank you for this!

**Comment by ajitid** [comment]
Quick question @dwilches and @rdvencioneck, if "Initialization Sequence Completed" message appears at the end on `docker compose up`, does it mean the VPN is connected?

**Comment by dwilches** [comment]
Sorry. It's been some months since I've not used this script so I don't
remember.

**Comment by ajitid** [comment]
That's fine @dwilches, thanks for replying back. I googled and found that "Initialization Sequence Completed" means I've connected to VPN. But as I don't have enough networking knowledge, I _think_ the n/w requests I'm making on my host are still not being routed to the VPN (and thus are not resolving).

**Pull request merged**
